<?php

return [
    'name' => 'Juan Moreno',
    'title' => 'Desarrollador Full Stack',
    'email' => 'mbappejuan464@gmail.com',
    'github' => 'https://github.com/TheJuanJo1',
    'instagram' => 'https://instagram.com/ejemplo_usuario',
    'seo' => [
        'title' => 'Juan Moreno | Desarrollador Full Stack',
        'description' => 'Portafolio profesional de Juan Moreno — Desarrollador Full Stack especializado en Laravel, PHP, JavaScript y soluciones web para sectores educativo y empresarial.',
        'og_image' => '/images/og-preview.svg',
    ],
    'hero' => [
        'bio' => 'Soy desarrollador de software con experiencia en la creación de aplicaciones web, sistemas educativos y soluciones empresariales utilizando tecnologías modernas de frontend y backend.',
        'tech_highlight' => ['Laravel', 'PHP', 'JavaScript', 'Node.js', 'MySQL', 'MariaDB', 'Tailwind CSS'],
    ],
    'about' => [
        'paragraphs' => [
            'Soy desarrollador de software con experiencia en el desarrollo de aplicaciones web para los sectores educativo y empresarial.',
            'He participado en la creación de plataformas de gestión académica, sistemas de evaluación institucional y soluciones de facturación electrónica utilizando tecnologías modernas tanto en frontend como en backend.',
        ],
        'experience' => ['Laravel', 'PHP', 'JavaScript', 'Node.js', 'Tailwind CSS', 'Bootstrap', 'MySQL', 'MariaDB'],
        'goal' => 'Mi objetivo es continuar fortaleciendo mis habilidades como desarrollador Full Stack y participar en proyectos que generen impacto real mediante la tecnología.',
    ],
    'technologies' => [
        'Frontend' => [
            ['name' => 'HTML5', 'icon' => 'html5', 'color' => '#E34F26'],
            ['name' => 'CSS3', 'icon' => 'css3', 'color' => '#1572B6'],
            ['name' => 'JavaScript', 'icon' => 'javascript', 'color' => '#F7DF1E'],
            ['name' => 'Tailwind CSS', 'icon' => 'tailwindcss', 'color' => '#06B6D4'],
            ['name' => 'Bootstrap', 'icon' => 'bootstrap', 'color' => '#7952B3'],
        ],
        'Backend' => [
            ['name' => 'PHP', 'icon' => 'php', 'color' => '#777BB4'],
            ['name' => 'Laravel', 'icon' => 'laravel', 'color' => '#FF2D20'],
            ['name' => 'Node.js', 'icon' => 'nodedotjs', 'color' => '#339933'],
        ],
        'Bases de Datos' => [
            ['name' => 'MySQL', 'icon' => 'mysql', 'color' => '#4479A1'],
            ['name' => 'MariaDB', 'icon' => 'mariadb', 'color' => '#003545'],
        ],
        'Herramientas' => [
            ['name' => 'Git', 'icon' => 'git', 'color' => '#F05032'],
            ['name' => 'GitHub', 'icon' => 'github', 'color' => '#181717'],
            ['name' => 'Composer', 'icon' => 'composer', 'color' => '#885630'],
            ['name' => 'Vite', 'icon' => 'vite', 'color' => '#646CFF'],
            ['name' => 'Visual Studio Code', 'icon' => 'visualstudiocode', 'color' => '#007ACC'],
            ['name' => 'XAMPP', 'icon' => 'apache', 'color' => '#D22128'],
            ['name' => 'Hostinger', 'icon' => 'cloudflare', 'color' => '#673DE6'],
        ],
    ],
    'skills' => [
        ['name' => 'Laravel', 'level' => 90],
        ['name' => 'PHP', 'level' => 90],
        ['name' => 'JavaScript', 'level' => 85],
        ['name' => 'HTML5', 'level' => 90],
        ['name' => 'CSS3', 'level' => 85],
        ['name' => 'Tailwind CSS', 'level' => 85],
        ['name' => 'Node.js', 'level' => 75],
        ['name' => 'MySQL', 'level' => 85],
        ['name' => 'MariaDB', 'level' => 80],
        ['name' => 'Git', 'level' => 80],
    ],
    'stats' => [
        ['value' => 3, 'suffix' => '+', 'label' => 'Proyectos principales desarrollados'],
        ['value' => 10, 'suffix' => '+', 'label' => 'Tecnologías utilizadas'],
        ['value' => 100, 'suffix' => '%', 'label' => 'Compromiso con la calidad'],
        ['value' => null, 'text' => 'Full Stack', 'subtext' => 'Developer', 'label' => ''],
    ],
    'projects' => [
        [
            'slug' => 'piar',
            'name' => 'Sistema PIAR',
            'featured' => false,
            'description' => 'Sistema web para la gestión y seguimiento de estudiantes con necesidades educativas especiales.',
            'technologies' => ['Laravel', 'PHP', 'JavaScript', 'HTML5', 'CSS3', 'Bootstrap', 'MySQL'],
            'features' => [
                'Gestión de estudiantes',
                'Remisiones institucionales',
                'Anexos PIAR',
                'Seguimiento académico',
                'Gestión de usuarios y roles',
                'Reportes administrativos',
            ],
            'gradient' => 'from-blue-600/20 to-indigo-600/20',
            'accent' => 'blue',
        ],
        [
            'slug' => 'evaluacion',
            'name' => 'Sistema de Evaluación de Desempeño',
            'featured' => false,
            'description' => 'Aplicación web desarrollada para gestionar procesos de evaluación institucional de docentes y funcionarios.',
            'technologies' => ['Laravel', 'PHP', 'JavaScript', 'HTML5', 'CSS3', 'Bootstrap', 'MySQL'],
            'features' => [
                'Evaluaciones institucionales',
                'Escalas de valoración',
                'Gestión de usuarios',
                'Formularios dinámicos',
                'Reportes',
                'Roles y permisos',
            ],
            'gradient' => 'from-violet-600/20 to-purple-600/20',
            'accent' => 'violet',
        ],
        [
            'slug' => 'fluxdata',
            'name' => 'FluxData - Sistema de Facturación Electrónica',
            'featured' => true,
            'description' => 'Sistema empresarial enfocado en la visualización y gestión de información relacionada con procesos de facturación electrónica mediante una interfaz moderna e intuitiva.',
            'technologies' => ['HTML5', 'CSS3', 'JavaScript', 'Tailwind CSS', 'Node.js', 'Vite', 'MariaDB'],
            'features' => [
                'Dashboard administrativo',
                'Indicadores empresariales',
                'Gestión de facturas electrónicas',
                'Administración de clientes',
                'Tablas dinámicas',
                'Diseño responsivo',
            ],
            'gradient' => 'from-cyan-500/30 via-blue-500/30 to-violet-600/30',
            'accent' => 'cyan',
        ],
    ],
    'solutions' => [
        [
            'icon' => '🎓',
            'title' => 'Soluciones Educativas',
            'projects' => ['Sistema PIAR', 'Sistema de Evaluación de Desempeño'],
            'description' => 'Soluciones orientadas a optimizar procesos académicos, seguimiento estudiantil y evaluación institucional.',
        ],
        [
            'icon' => '🏢',
            'title' => 'Soluciones Empresariales',
            'projects' => ['FluxData'],
            'description' => 'Soluciones orientadas a la gestión administrativa, facturación electrónica y visualización de indicadores empresariales.',
        ],
    ],
    'nav' => [
        ['href' => '#inicio', 'label' => 'Inicio'],
        ['href' => '#sobre-mi', 'label' => 'Sobre mí'],
        ['href' => '#tecnologias', 'label' => 'Tecnologías'],
        ['href' => '#habilidades', 'label' => 'Habilidades'],
        ['href' => '#proyectos', 'label' => 'Proyectos'],
        ['href' => '#contacto', 'label' => 'Contacto'],
    ],
];
